# Generated by Django 6.0.5 on 2026-05-28 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="почта"
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужчина"), ("F", "Женщина")],
                        default="M",
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                ("weight", models.FloatField(verbose_name="Вес")),
                ("height", models.FloatField(verbose_name="Рост")),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Возраст",
                    ),
                ),
                (
                    "activity_status",
                    models.IntegerField(
                        choices=[
                            (1, "Нет активности"),
                            (2, "Легкая активность"),
                            (3, "Умеренная активность"),
                            (4, "Высокая активность"),
                            (5, "Очень высокая активность"),
                        ],
                        default=1,
                        verbose_name="Статус физической активности",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("loss", "Снижение веса"),
                            ("maintain", "Поддержание веса"),
                            ("gain", "Набор веса"),
                        ],
                        default="maintain",
                        max_length=10,
                        verbose_name="Цель",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активированный"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Работник"),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
