# Generated by Django 6.0.5 on 2026-05-29 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
    ]
