# Generated by Django 6.0.5 on 2026-06-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, upload_to="profile_pics/", verbose_name="Фото профиля"
            ),
        ),
    ]
