# Generated by Django 6.0.5 on 2026-05-28 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Публикация", "verbose_name_plural": "Публикации"},
        ),
    ]
